name: k2lcs

channels:
  - astropy

dependencies:
  - python=2.7
  - astropy
  - numpy
  - matplotlib
  - scipy
  - astroML
  - pip:
    - supersmoother
    - astroML
    - astroML_addons
    - gatspy
    - ez_setup
    - pywcsgrid2
    - K2fov
    
